package:
  name: diffpy.srfit
  ## Use __conda_version__.txt.
  # version: 1.0.post32

source:
  git_url: https://github.com/diffpy/diffpy.srfit
  git_rev: e130b6bcc582ce44a9132fed38c96d5da625772b
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - numpy >=1.3

test:
  # Python imports
  imports:
    - diffpy.srfit
    - diffpy.srfit.equation
    - diffpy.srfit.equation.literals
    - diffpy.srfit.equation.visitors
    - diffpy.srfit.fitbase
    - diffpy.srfit.interface
    - diffpy.srfit.pdf
    # - diffpy.srfit.sas
    - diffpy.srfit.structure
    - diffpy.srfit.tests
    - diffpy.srfit.util

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - diffpy.structure
    - pyobjcryst
    - diffpy.srreal

about:
  home: https://github.com/diffpy/diffpy.srfit/
  summary: Framework for complex modeling and atomic structure optimization.
  license: Modified BSD License
  license_file: LICENSE.txt

# See http://docs.continuum.io/conda/build.html
# for more information about meta.yaml.
